### ISSUE TITLE
Build fails with error in Kayak-mapview

### ISSUE THREAD

**Issue by RaBa64** [dschanoeh/Kayak#30]
Build fails with error in Kayak-mapview:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project Kayak-mapview: Compilation failure
[ERROR] /home/ralf/src/Kayak/Kayak-mapview/target/generated-sources/annotations/com/github/kayak/mapview/Bundle.java:[3,18] cannot find symbol
[ERROR]   symbol:   class Generated
[ERROR]   location: package javax.annotation

I did a clean "git clone" and used "mvn clean install".
Other modules had no build problem:

[INFO] Kayak .............................................. SUCCESS [  0.227 s]
[INFO] Kayak - Platform application branding resources .... SUCCESS [  2.342 s]
[INFO] Kayak-core NetBeans Module ......................... SUCCESS [  3.980 s]
[INFO] Kayak-ui NetBeans Module ........................... SUCCESS [  3.597 s]
[INFO] Kayak-logging NetBeans Module ...................... SUCCESS [  1.163 s]
[INFO] Kayak-kcd NetBeans Module .......................... SUCCESS [  2.680 s]
[INFO] Kayak-mapview NetBeans Module ...................... FAILURE [  0.459 s]
[INFO] Kayak - NetBeans Platform based application ........ SKIPPED

**Comment by dustindavis** [comment]
I am facing the same issue

**Comment by bcovenant** [comment]
I am having the same error. Any update?

**Comment by RUNTAODUAN** [comment]
same issue for me

**Comment by oemunlock** [comment]
I fixed this issue with this diff in pom.xml
`
$ git diff pom.xml
diff --git a/pom.xml b/pom.xml
index 57b0fad..392bfb3 100644
--- a/pom.xml
+++ b/pom.xml
@@ -43,6 +43,11 @@
             <version>4.12</version>
             <scope>test</scope>
         </dependency>
+        <dependency>^M
+             <groupId>javax.annotation</groupId>^M
+            <artifactId>javax.annotation-api</artifactId>^M
+            <version>1.2</version>^M
+        </dependency>^M
     </dependencies>
 
     <build>
`

**Comment by oemunlock** [comment]
I fixed this issue with this diff in pom.xml
```
$ git diff pom.xml
diff --git a/pom.xml b/pom.xml
index 57b0fad..392bfb3 100644
--- a/pom.xml
+++ b/pom.xml
@@ -43,6 +43,11 @@
             <version>4.12</version>
             <scope>test</scope>
         </dependency>
+        <dependency>^M
+             <groupId>javax.annotation</groupId>^M
+            <artifactId>javax.annotation-api</artifactId>^M
+            <version>1.2</version>^M
+        </dependency>^M
     </dependencies>
 
     <build>
```

**Comment by ccescobar** [comment]
Thank you OEMUnlock!

**Comment by ahhmino** [comment]
I tried  this solution

> I fixed this issue with this diff in pom.xml
> 
> ```
> $ git diff pom.xml
> diff --git a/pom.xml b/pom.xml
> index 57b0fad..392bfb3 100644
> --- a/pom.xml
> +++ b/pom.xml
> @@ -43,6 +43,11 @@
>              <version>4.12</version>
>              <scope>test</scope>
>          </dependency>
> +        <dependency>^M
> +             <groupId>javax.annotation</groupId>^M
> +            <artifactId>javax.annotation-api</artifactId>^M
> +            <version>1.2</version>^M
> +        </dependency>^M
>      </dependencies>
>  
>      <build>
> ```

but my output was instead:

diff --git a/pom.xml b/pom.xml
index 57b0fad..7e621a1 100644
--- a/pom.xml
+++ b/pom.xml
@@ -166,4 +166,4 @@
         <developerConnection>scm:git:git://github.com/dschanoeh/Kayak.git</developerConnection>
     </scm>
     <prerequisites/>
-</project>
\ No newline at end of file
+</project>^M

And the build still fails in the same way. Am I running this solution wrong?

**Comment by dschanoeh** [comment]
@oemunlock thanks for the fix. Added to the repository now.
